version: "3.8"

services:
  printer3d:
    build: .
    image: patrykb/person_register_image
    container_name: person_register_container
    restart: always
    networks:
      - patryknetwork
    ports:
      - 8080:8080
    depends_on:
      - mariadb

  mariaDB:
    image: mariadb
    container_name: person_register_maria
    restart: always
    networks:
      - patryknetwork
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: admin_patryk2
      MARIADB_ROOT_PASSWORD: admin123kot
    volumes:
      - person-registersion:/build/libs/mariadb/data

volumes:
  person-registersion:

networks:
  patryknetwork: